export const SET_IS_CHECKING_USER = 'SET_IS_CHECKING_USER';
export const SET_FB_AUTH_USER = 'SET_FB_AUTH_USER';
export const SET_USER = 'SET_USER';
export const SET_SIGNUP_NAMES = 'SET_SIGNUP_NAMES';
