export const SET_IS_CHECKING_USER = 'SET_IS_CHECKING_USER';
export const SET_FB_AUTH_USER = 'SET_FB_AUTH_USER';
export const SET_USER = 'SET_USER';

export const UPDATE_USER_PROFILE_PICTURE = 'UPDATE_USER_PROFILE_PICTURE';
export const UPDATE_USER_FOLLOWING = 'UPDATE_USER_FOLLOWING';
export const UPDATE_PREV_USER_FOLLOWING = 'UPDATE_PREV_USER_FOLLOWING';
