export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE';
export const SET_IS_SUBMITTING = 'SET_IS_SUBMITTING';
export const SET_SUCCESS_SNACKBAR = 'SET_SUCCESS_SNACKBAR';
export const SET_FAILURE_SNACKBAR = 'SET_FAILURE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';
