export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE';
export const SET_IS_SUBMITTING = 'SET_IS_SUBMITTING';

//SNACKBAR
export const SET_SUCCESS_SNACKBAR = 'SET_SUCCESS_SNACKBAR';
export const SET_FAILURE_SNACKBAR = 'SET_FAILURE_SNACKBAR';
export const REMOVE_SNACKBAR = 'REMOVE_SNACKBAR';

//DIALOGS
export const OPEN_CLICKED_POST_DIALOG = 'OPEN_CLICKED_POST_DIALOG';
export const CLOSE_CLICKED_POST_DIALOG = 'CLOSE_CLICKED_POST_DIALOG';

export const OPEN_POST_UPLOAD_DIALOG = 'OPEN_POST_UPLOAD_DIALOG';
export const CLOSE_POST_UPLOAD_DIALOG = 'CLOSE_POST_UPLOAD_DIALOG';

export const OPEN_POST_EDIT_DIALOG = 'OPEN_POST_EDIT_DIALOG';
export const CLOSE_POST_EDIT_DIALOG = 'CLOSE_POST_EDIT_DIALOG';

export const OPEN_CONFIRMATION_DIALOG = 'OPEN_CONFIRMATION_DIALOG';
export const CLOSE_CONFIRMATION_DIALOG = 'CLOSE_CONFIRMATION_DIALOG';
export const SET_CONFIRMATION_DIALOG = 'SET_CONFIRMATION_DIALOG';
