export const SET_SELECTED_FILE = 'SET_SELECTED_FILE';
export const SET_DATA_URL = 'SET_DATA_URL';
export const CANCEL_FILE = 'CANCEL_FILE';
export const CLEAR_FORM = 'CLEAR_FORM';
export const SET_POST_DESCRIPTION = 'SET_POST_DESCRIPTION';
export const SET_CONFIRMED_FILE = 'SET_CONFIRMED_FILE';
