export const SET_FILE_SUCCESS = 'SET_FILE_SUCCESS';
export const SET_FILE_FAIL = 'SET_FILE_FAIL';
export const SET_DATA_URL = 'SET_DATA_URL';
export const CANCEL_FILE = 'CANCEL_FILE';
export const RESET_FORM = 'RESET_FORM';
export const SET_POST_DESCRIPTION = 'SET_POST_DESCRIPTION';
export const SET_CONFIRMED_FILE = 'SET_CONFIRMED_FILE';
